[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "curve-zkp"
version = "0.1.0"

[dependencies]
blake2 = "0.8"
ff-zeroize = "0.6"
pairing-plus = "0.19"
